(add-to-list 'load-path "~/.emacs.d/config/")
(add-to-list 'load-path "~/.emacs.d/custom/")

(load "packages")
(load "ui")
(load "varia")
(load "completion")
(load "coding")
(load "git")
(load "web")
(load "projects")

(load "movelines")
(load "rename-file-buffer")
(load "autosave")
