(setq max-lisp-eval-depth 1500
      max-specpdl-size    3000)

;(package-initialize)

(add-to-list 'load-path "~/.emacs.d/config/")
(add-to-list 'load-path "~/.emacs.d/custom/")

(load "init-packages")
(load "init-ui")
(load "init-varia")
(load "init-editor")
(load "init-ido")
(load "init-company")
(load "init-flycheck")
(load "init-git")
(load "init-js")
(load "init-purescript")
(load "init-md")
(load "init-projectile")
(load "init-neotree")
(load "init-modeline")
(load "init-persistent-scratch")
(load "init-ag")
(load "init-helm")
(load "init-web")

(load "movelines")
(load "rename-file-buffer")
(load "autosave")
